# Generated by Django 4.1.4 on 2022-12-29 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='size_l',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_m',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_s',
        ),
        migrations.CreateModel(
            name='ItemSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_s', models.BooleanField(default=True)),
                ('size_m', models.BooleanField(default=True)),
                ('size_l', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reek.item')),
            ],
        ),
    ]
