# Generated by Django 4.1.4 on 2022-12-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0002_remove_item_size_l_remove_item_size_m_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemSizes',
            new_name='ItemSize',
        ),
    ]
