# Generated by Django 4.1.4 on 2022-12-29 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0005_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='reek.item'),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sizes', to='reek.item'),
        ),
    ]
