# Generated by Django 4.1.4 on 2023-01-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0007_category_rocking_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsize',
            name='size_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size_s',
            field=models.BooleanField(default=False),
        ),
    ]
