# Generated by Django 4.1 on 2023-01-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0009_alter_itemsize_size_l_alter_itemsize_size_m_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='category',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
