# Generated by Django 4.1 on 2023-01-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0010_alter_category_options_category_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='checked',
        ),
    ]
