# Generated by Django 4.1.4 on 2023-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0013_basket_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=5),
        ),
    ]
