# Generated by Django 4.1.4 on 2023-01-17 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reek', '0019_alter_payment_is_paid_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reek.basket'),
        ),
    ]
